name: ðŸš€ Run API Migrations

on:
  push:
    branches: [main]

jobs:
  web-deploy:
    name: ðŸ›° API Migrations
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '#migrate') }}
    steps:
      - name: check
        run: |
          echo ${{ secrets.COMPOSER }} | base64 --decode > ok.txt
          cat ok.txt
      - name: ðŸ“¦ Run Migrate
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SOP_HOST }}
          username: ${{ secrets.SOP_SSH_USERNAME }}
          password: ${{ secrets.SOP_SSH_PASSWORD }}
          port: ${{ secrets.SOP_SSH_PORT }}
          script: pwd && cd public_html/kah/fireapp && php artisan migrate:fresh --seed
